# Generated by Django 4.2.1 on 2023-05-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_rating_score'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
